name: CI - Anemia Predictor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Warn about style issues
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

    - name: Run model training
      run: |
        python train_model.py

    - name: Confirm Streamlit script is syntactically correct
      run: |
        python -m py_compile app.py
